export enum Colors {
  Primary = "primary",
  Secondary = "secondary",
  PrimaryDark = "primary.dark",
  PrimaryContrastText = "primary.contrastText",
  Info = "info",
  InfoDark = "info.dark",
  InfoContrastText = "info.contrastText",
  Active = "active",
  Danger = "#ff474c",
  Gray = "#8b8b8b",
  Light = "#ECDFCC",
  PrimaryLight = "primary.light",
  SecondaryLight = "#50e3b7",
  TriadicLight2 = "#7ce350",
  TriadicLight = "#e3b750",
  TriadicLight900 = "#dd7400",
  White = "#ffffff",
}
