import type { Metadata } from "next";
import { nunito, quicksand } from "@/shared/fonts";
import "@/shared/styles/globals.scss";

export const metadata: Metadata = {
  title: "Dating App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} ${nunito.variable}`}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
