import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "../globals.scss";

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Dating App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${nunito_sans.className}`}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
