import type { Metadata } from "next";
import "@/shared/styles/globals.scss";
import { nunito, quicksend } from "@/shared/fonts";



export const metadata: Metadata = {
  title: "Dating App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${quicksend.variable}`}>{children}</body>
    </html>
  );
};

export default RootLayout;
